- op: replace
  path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
  value: letsencrypt-prd
- op: replace
  path: /spec/rules/0/host
  value: holefeeder.drifterapps.app
- op: replace
  path: /spec/tls/0/hosts/0
  value: holefeeder.drifterapps.app
