name: Force PowerSync Resync

on:
  workflow_dispatch:

jobs:
  force-resync:
    name: Force Resync
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      - name: Add host key
        run: ssh-keyscan -H ${{ vars.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts

      - name: Update Rows to Trigger Sync
        run: |
          ssh ${{ vars.DIGITALOCEAN_USER }}@${{ vars.DIGITALOCEAN_HOST }} "
            cd ~ &&
            docker compose -f docker-compose.yaml -f docker-compose.Production.yaml restart powersync &&
            docker compose -f docker-compose.yaml -f docker-compose.Production.yaml exec -T postgres bash -c 'psql -U \"\$POSTGRES_APP_USER\" -d \"\$POSTGRES_APP_DB\" -c \"BEGIN; UPDATE accounts SET name = name; UPDATE categories SET name = name; UPDATE transactions SET description = description; UPDATE cashflows SET description = description; UPDATE store_items SET code = code; COMMIT;\"'
          "
