name: mutation-tests

on:
  push:
    branches: [main]
    paths-ignore:
      [
        "docs/**",
        ".vscode/**",
        "**/ci-cd.yml",
        "**/codeql-analysis.yml",
        "**/dependabot.yml",
        "**/linter.yml",
        "**/unit-test-results.yml",
        "kubernetes/**",
      ]

  pull_request:
    paths-ignore:
      [
        "docs/**",
        ".vscode/**",
        "**/ci-cd.yml",
        "**/codeql-analysis.yml",
        "**/dependabot.yml",
        "**/linter.yml",
        "**/unit-test-results.yml",
        "kubernetes/**",
      ]

  workflow_dispatch:

concurrency:
  group: mutation-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stryker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Stryker.NET global tool
        run: dotnet tool install --global dotnet-stryker

      - name: Restore packages
        run: dotnet restore

      - name: Run Mutation tests
        if: (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch')
        run: dotnet stryker --reporter "dashboard" --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ github.ref_name }}

      - name: Run Mutation tests
        if: github.event_name == 'pull_request'
        run: dotnet stryker --reporter "dashboard" --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --with-baseline:${{ github.event.pull_request.base.ref }} --version ${{ github.event.pull_request.head.ref }}
